# Site settings
title: Gabriel Gebril
email: contact@gabrielg.me
url: gabrielg.me
description: "Gabriel Gebril is a researcher and educator studying the use of games in education, healthcare, and persuasion."
keywords: "Gabriel, Gebril, Jibreel, Jibril, games, education, healthcare, persuasion"
skills: "Web - Data - Game - FOSS"
meta_author: Gebril Gabriel

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 003f5c #80B3FF
  primary-rgb: 003f5c #"128,179,255"
  secondary: ba5715 #Bloodhound  
  secondary-dark: a14b11  #A2122F

# Footer settings
footer:
  copyright: Gabriel Gebril
  location: Location
  social: Around the Web
  credits: Email

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://x.com/Gebril_Gabriel
  - title: tiktok
    url: https://www.tiktok.com/@gabriel.gebril
  - title: github
    url: https://github.com/Gabriel-Gebril

# Postal address (add as many lines as necessary)
address:
  - line: St. Catharines

# Credits content
credits: 'contact@gabrielg.me'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
